# Generated by Django 5.2.7 on 2025-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='symbol',
            field=models.CharField(default='BTCUSDT', help_text='Symbol or pair, e.g. BTCUSDT or OANDA:EUR_USD', max_length=64),
            preserve_default=False,
        ),
    ]
